# Generated by Django 4.1.7 on 2023-03-12 15:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='about_image/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='classes_image/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('yoshi', models.CharField(max_length=50)),
                ('jami', models.CharField(max_length=50)),
                ('vaqti', models.CharField(max_length=100)),
                ('harajat', models.CharField(max_length=50)),
            ],
        ),
    ]
