# Generated by Django 4.1.7 on 2023-03-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidKinder_app', '0002_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='teachers_image/')),
                ('name', models.CharField(max_length=50)),
                ('kasb', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
